version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/.github/actions/release/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/.github/actions/version/"
    schedule:
      interval: "daily"
