name: SxDashPlus Release Action
description: Automatic GitHub release when manifest.json version changes
branding:
  color: red
  icon: archive
inputs:
  currentVersion:
    description: New version.
    required: true
  previousVersion:
    description: Version of latest release.
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
