name: SxDashPlus Release Action
description: Automatic GitHub release when manifest.json version changes
branding:
  color: red
  icon: archive
inputs:
  path:
    description: Path of the manifest.json file that will be examined. Defaults to GITHUB_WORKSPACE.
    default: ${{ github.workspace }}
    required: false
  token:
    description: Personal access token. Defaults to GITHUB_TOKEN.
    default: ${{ github.token }}
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'