on: [push]

jobs:
  auto_release:
    runs-on: ubuntu-latest
    name: Create release if version changed
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: xxx0365/sx-dash-plus-release-action@v1.0
