on: [push]

jobs:
  auto_release:
    runs-on: ubuntu-latest
    name: Create release if version changed
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release
        id: release
        uses: xxx0365/sx-dash-plus-release-action@v1.0
