on:
  push:
    branches:
      - master

jobs:
  auto_release:
    runs-on: ubuntu-latest
    name: Create release if version changed
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build
        run: yarn build

      - name: Release
        uses: ./.github/actions/release
